package com.ws.appversion.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ws.appversion.db.bean.Eo_ApkDownloadInfo;

import com.ws.appversion.db.dao.Eo_ApkDownloadInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eo_ApkDownloadInfoDaoConfig;

    private final Eo_ApkDownloadInfoDao eo_ApkDownloadInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eo_ApkDownloadInfoDaoConfig = daoConfigMap.get(Eo_ApkDownloadInfoDao.class).clone();
        eo_ApkDownloadInfoDaoConfig.initIdentityScope(type);

        eo_ApkDownloadInfoDao = new Eo_ApkDownloadInfoDao(eo_ApkDownloadInfoDaoConfig, this);

        registerDao(Eo_ApkDownloadInfo.class, eo_ApkDownloadInfoDao);
    }
    
    public void clear() {
        eo_ApkDownloadInfoDaoConfig.clearIdentityScope();
    }

    public Eo_ApkDownloadInfoDao getEo_ApkDownloadInfoDao() {
        return eo_ApkDownloadInfoDao;
    }

}
